---
- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure dependencies for installation are installed"
  become: true
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - gnupg
      - python3-debian
- name: "Ensure Docker APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/ubuntu"
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    architectures: amd64
  when: env_common_install_docker == true
