---
#- name: "Print debug info"
#  debug:
#    msg: "Configuring role 'env-common' for user '{{ env_common_username }}'"
- include: software.yml
- include: git.yml
- include: zsh.yml
# Disabled because it overwrites any changes made to PATH and exports configured by other Ansible tasks.
#- name: ".bash_aliases"
#  copy:
#    src: bash_aliases
#    dest: /home/{{ env_common_username }}/.bash_aliases
