---
- name: "Install common packages"
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - aptitude
      - containerd.io # Related to Docker
      - curl
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - git
      - htop
      - joe
      - net-tools
      - ssh
      - wget
# - name: "Install common packages (Ubuntu)"
#   become: true
#   apt:
#     name: ...
#   when: ansible_distribution == "Ubuntu"
