---
- name: "Refresh apt cache"
  become: true
  apt:
    update_cache: true
- name: "Install common packages"
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - aptitude
      - bat
      - curl
      - git
      - htop
      - joe
      - net-tools
      - ssh
      - wget
