---
- name: "Refresh apt cache"
  become: true
  apt:
    update_cache: true
- name: "Install common packages"
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - curl
    - wget
    - git
    - ssh
    - htop
    - joe
