---
- name: "Install common packages"
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - aptitude
      - curl
      - direnv
      - git
      - htop
      - joe
      - language-pack-en
      - nano
      - net-tools
      - ssh
      - wget
- name: "Install Docker packages"
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
  when: env_common_install_docker == true
# - name: "Install common packages (Ubuntu)"
#   become: true
#   apt:
#     name: ...
#   when: ansible_distribution == "Ubuntu"
