---
- name: "Install zsh"
  become: true
  apt:
    name: zsh
- name: "Check out the zsh configuration repository"
  git:
    repo: https://scheleaap@github.com/scheleaap/zsh-config.git
    dest: /home/{{ env_common_username }}/.zsh
    version: master
- name: "Configure the zsh configuration repository"
  git_config:
    repo: /home/{{ env_common_username }}/.zsh
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: local
  with_items:
    - { name: "user.name", value: "{{ git_user_name }}" }
    - { name: "user.email", value: "{{ git_user_email }}" }
- name: "Set up .zshrc"
  file:
    state: link
    src: /home/{{ env_common_username }}/.zsh/.zshrc
    dest: /home/{{ env_common_username }}/.zshrc
- name: "Configure zsh as the default shell"
  become: true
  user:
    name: "{{ env_common_username }}"
    shell: /usr/bin/zsh
