---
- name: Ensure /home/{{ user_username }}/bin exists
  file:
    path: /home/{{ user_username }}/bin
    state: directory
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: Ensure /home/{{ user_username }}/.local/share/applications exists
  file:
    path: /home/{{ user_username }}/.local/share/applications
    state: directory
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: "Unpack Maven"
  unarchive:
    copy: true
    src: apache-maven-3.3.9-bin.tar.gz
    dest: /home/{{ user_username }}/bin
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: "Add Maven to PATH"
  lineinfile:
    line: "PATH=$PATH:~/bin/apache-maven-3.3.9/bin"
    dest: /home/{{ user_username }}/.bashrc
- name: "Set M2_HOME"
  lineinfile:
    line: "M2_HOME=/home/{{ user_username }}/bin/apache-maven-3.3.9"
    dest: /home/{{ user_username }}/.bashrc
- name: Ensures /home/{{ user_username }}/.m2 exists
  file:
    path: /home/{{ user_username }}/.m2
    state: directory
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: "Configure Maven"
  copy:
    src: settings.xml
    dest: /home/{{ user_username }}/.m2/settings.xml
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
