---
- name: Ensure /home/{{ user_username }}/bin exists
  file:
    path: /home/{{ user_username }}/bin
    state: directory
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: Ensure /home/{{ user_username }}/.local/share/applications exists
  file:
    path: /home/{{ user_username }}/.local/share/applications
    state: directory
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: "Unpack Eclipse"
  unarchive:
    copy: true
    src: eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
    dest: /home/{{ user_username }}/bin
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
- name: "Add Eclipse to PATH"
  lineinfile:
    line: "PATH=$PATH:~/bin/eclipse"
    dest: /home/{{ user_username }}/.bashrc
- name: "Add Eclipse shortcut for the Ubuntu launcher"
  template:
    src: eclipse.desktop
    dest: /home/{{ user_username }}/.local/share/applications/eclipse.desktop
    mode: 0755
    owner: "{{ user_username }}"
    group: "{{ user_username }}"
